### ISSUE TITLE
TODO - Settings

### ISSUE THREAD

**Issue by Scaratek** [NocturaProxy/Frontend#3]
Not an issue, Just to keep track of what is and what isnt dont

- [X] AB Cloaker
- [X] Title Cloaker
- [x] Title Cloaker Using Forms
- [x] Icon Cloaker Using Forms
- [x] Local Storage Usage
- [x] Border Around Cloaker Settings
- [x] Theme Swapper
